<x-forge>
    <x-forge-heading>Username</x-forge-heading>
    <x-forge-container>
        <x-forge-header>
            <x-forge-button-generate>Generate</x-forge-button-generate>
            <x-forge-button-copy>Copy</x-forge-button-copy>
        </x-forge-header>
        <x-forge-input/>
    </x-forge-container>
</x-forge>
